# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node:16

pipelines:
  default:
      - step:
          name: 'Build'
          caches:
            - node
          script:
            - npm install
            - npm run build
        - step:
            - script:
                - ls
